### ISSUE TITLE
Meet error: ld.lld: error: undefined symbol: std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()

### ISSUE THREAD

**Issue by Gy-Hu** [novt-vtable-less-compiler/novt-llvm#1]
Hi, I met error when I try to run the test sample script. It happens when compile the test22

```shell
ld.lld: error: undefined symbol: std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()
>>> referenced by ld-temp.o
>>>               lto.tmp:(main)
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
```

Any idea how to solve this?

**Comment by MarkusBauer** [comment]
Hi, 
I would guess that the c++ standard library (libstdc++) is not properly compiled and installed. NoVT needs a protected version of that library. In section "Build NoVT", did step 2 complete without errors?

After installation, you can run this command to check if the standard library is properly installed (step 3):
```
$ ls -lh /usr/novt-lib/
total 8,7M
drwxrwxr-x 3 XXX XXX 4,0K Okt 22  2020 include
-rw-r--r-- 1 XXX XXX 6,7M Okt 22  2020 libstdc++.a
-rw-r--r-- 1 XXX XXX 1,1M Okt 22  2020 libstdc++fs.a
-rw-r--r-- 1 XXX XXX 1,0M Okt 22  2020 libsupc++.a
```

**Comment by Gy-Hu** [comment]
Thanks, I solved this by installing on my real ubuntu device instead of installing on docker.

By the way, after running through all the test, I am still confused that how I knew the tool has worked or not? I have read the source code in `test_sample.py`, but it shows that it will check the output of two compiler is the same or not.

Is there any way to input a attack code sample and test whether it works on that?

**Comment by MarkusBauer** [comment]
There is no automated test for that, but you can check very simply if a binary is protected or not, as long as it's not stripped. Protected binaries should contain dispatcher functions named `__novt.<...>`. For example:

```
$ strings ./test1 | grep "__novt"
__novt.1A.1gl
__novt.1A.3fool
__novt.1A.D0v
__novt.1B.3fool
__novt.N10__cxxabiv117__class_type_infoE.K11__do_upcastPKN10__cxxabiv117__class_type_infoEPKvRNS0_15__upcast_resultE
__novt.St9exception.K4whatv
__novt.St9type_info.K10__do_catchPKSt9type_infoPPvj
__novt.St9type_info.K11__do_upcastPKN10__cxxabiv117__class_type_infoEPPv
__novt.St9type_info.K14__is_pointer_pv
```

If a binary is protected, there will be results. If it's unprotected (or does not contain virtual dispatch), the result list will be empty.
